#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

robot_radius: 0.3 #0.8   #930mm x 699mm x349mm
# footprint: [[0.72,0.00],[0.00,-0.35],[-0.2,0.00],[0.00,0.35]]

footprint_padding: 0.05 #0.08
map_type: voxel

# inflation_layer:
#   enabled:              true
#   cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
#   inflation_radius:     0.7  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"
  lethal_cost_threshold: 80 
