global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 1.5
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   # rolling_window: true
   # width: 100
   # height: 100
   resolution: 0.1 #0.05
   transform_tolerance: 5.0
   map_type: costmap
   plugins:
      - {name: static_layer,        type: "costmap_2d::StaticLayer"}
      # - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
      #- {name: costmap_prohibition_layer,       type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
      - {name: inflation_layer,     type: 'costmap_2d::InflationLayer'}

   inflation_layer:
      enabled:              true
      cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
      inflation_radius: 0.5 #1.0  # max. distance from an obstacle at which costs are incurred for planning paths.


GlobalPlanner:        
   allow_unknown: false 
